# Documentation:
#  https://fmu-docs.equinor.com/docs/grid3d-maps/
#  https://fmu-docs.equinor.com/docs/grid3d-maps/config-hc.html

title: Drogon

# dates are fetched from global_variables.yml file
input:
  fmu_global_config: fmuconfig/output/global_variables.yml
  dates:     !include_from   fmuconfig/output/global_variables_pred.yml::global.dates.ECLIPSE_PRED_DATES
  diffdates: !include_from   fmuconfig/output/global_variables_pred.yml::global.dates.ECLIPSE_PRED_DIFFDATES

# Zonation from file on yaml format
zonation:
  yamlfile: ../iter-0/rms/output/zone/zonation_ecl_map.yml

computesettings:
  mode: oil  # Choose oil, gas, or both
  critmode: No  # Compute mobile SOIL using SOGCR or SOWCR or None (sogcr, sowcr, No)
  method: use_poro
  zone: Yes  # compute for each zone
  all: Yes   # compute for all combined
  tuning:
    zone_avg: Yes   # yes = faster method ( 'ij' averaging vs 'xy' averaging )


# Map definition
mapsettings:
  xori: 456511
  xinc: 75
  yori: 5926880
  yinc: 75
  ncol: 143
  nrow: 161


output:
  mapfolder: fmu-dataio  # use this to export with metadata (data exported to share/results/maps)
  # mapfolder: share/results/maps  # use this to export without metadata
